### PR TITLE
Calculate bye score

### PR DESCRIPTION
**Pull request by giaunguyen2176**
Currently, score formula does not seems to take into consideration of bye match/games. But the scoring configuration object has allowed to configure score for each bye match/game. So adjust the formula to add points in such cases.

### CODE REVIEW

**Comment by slashinfty** [comment]
I'd prefer the following so players receive the correct amount of game points for a bye:

```ts
player.gamePoints += ((match.bye ? this.scoring.bye : this.scoring.win) * match.win) + (this.scoring.loss * match.loss) + (this.scoring.draw * match.draw);
```

**Comment by slashinfty** [comment]
Why would `match.win` be 0? See: [here](https://github.com/slashinfty/tournament-organizer/blob/main/src/components/Tournament.ts#L202), [here](https://github.com/slashinfty/tournament-organizer/blob/main/src/components/Tournament.ts#L296), and [here](https://github.com/slashinfty/tournament-organizer/blob/main/src/components/Tournament.ts#L888).

**Comment by giaunguyen2176** [comment]
@slashinfty you're right. I've updated the calculation. Take a look again please.

**Comment by slashinfty** [comment]
I will get v3.6.3 out later today with this included

**Pull request merged**
